### ISSUE TITLE
Can't compile due to missing compiler flag

### ISSUE THREAD

**Issue by Jakraes** [guzba/nimsimd#1]
So, basically there's this error shown in the image below when compiling:
![Screenshot_8](https://user-images.githubusercontent.com/70046168/184274045-fd4de5ae-bb3c-42b8-84b0-8562b604b4ac.png)

Which can be fixed by passing the --passC:-msse2 flag in the compiler (Credit to leorize for finding that out)

**Comment by guzba** [comment]
Hm, would you mind sharing what CPU and compile command you used? -msse2 is a default on 64 bit systems for everything I've ever seen.

**Comment by guzba** [comment]
I'm going to close this issue and open one on noisy. This repo (nimsimd) will never send flags to the compiler, it just provides bindings as mentioned in the readme.
