### ISSUE TITLE
M1 Mac runtimecheck Errors

### ISSUE THREAD

**Issue by miguelmartin75** [guzba/nimsimd#12]
With the following code:

```
import nimsimd/runtimecheck

let
  cpuHasAvx* = checkInstructionSets({AVX})
  cpuHasAvx2* = checkInstructionSets({AVX, AVX2})
```

This fails to compile: 

```
/Users/miguelmartin/.cache/nim/nimsimd_test_d/@m..@s..@s..@s..@s.nimble@spkgs2@snimsimd-1.2.5-9f919415ad69edb599c3362b0cc0fe0b044097c9@snimsimd@sruntimecheck.nim.c:130:10: error: invalid output constraint '=a' in asm
        :"=a"(eaxr), "=b"(ebxr), "=c"(ecxr), "=d"(edxr)
         ^
1 error generated.
Error: execution of an external compiler program 'clang -c  -w -ferror-limit=3 -pthread   -I/Users/miguelmartin/.choosenim/toolchains/nim-2.0.0/lib -I/Users/miguelmartin/repos/nim_playground/nimsimd_test/src -o /Users/miguelmartin/.cache/nim/nimsimd_test_d/@m..@s..@s..@s..@s.nimble@spkgs2@snimsimd-1.2.5-9f919415ad69edb599c3362b0cc0fe0b044097c9@snimsimd@sruntimecheck.nim.c.o /Users/miguelmartin/.cache/nim/nimsimd_test_d/@m..@s..@s..@s..@s.nimble@spkgs2@snimsimd-1.2.5-9f919415ad69edb599c3362b0cc0fe0b044097c9@snimsimd@sruntimecheck.nim.c' failed with exit code: 1
````

System Details:
- OS: MacOS 13.5
- CPU: M1 Max
- RAM: 64GB

Compiler version: 2.0

**Comment by guzba** [comment]
I have confirmed this works as expected on my M1 using `nim c -r examples/runtimecheck.nim` added https://github.com/guzba/nimsimd/pull/13

What is your compile command?

**Comment by guzba** [comment]
Ah, I'm guessing you are compiling as arm64. It is only possible to runtime check amd64 instruction sets. You'll need a `when defined(amd64):` block.

Edit: looks like I have that at the top of runtimecheck.nim to prevent this. Lets see what the compile command is.

**Comment by miguelmartin75** [comment]
It seems related to choosenim not providing an arm64 build (https://github.com/dom96/choosenim/issues/318). I'll install the compiler myself.

**Comment by guzba** [comment]
Ah, interesting. Lets see if anything changes with a fresh compiler build. Fortunately Nim makes that relatively straightforward imo.

**Comment by miguelmartin75** [comment]
Compiling & installing the nim compiler worked to resolve this (I can now use pixie!). Apologies for the noise.

**Comment by guzba** [comment]
All good, glad that fixed things and hopefully choosenim stuff will be sorted out soon too.
