### ISSUE TITLE
mm256_permute4x64_pd missing from avx2.nim

### ISSUE THREAD

**Issue by Asc2011** [guzba/nimsimd#20]
Hi guzba,

maybe found another glitch - `mm256_permute4x64_pd` for double-precision should be in `avx2.nim`. Though `mm256_permute4x64_epi64` + a cast will do exactly the same - so, maybe you left it intentionally ?

regards, andreas

**Comment by guzba** [comment]
Thanks for pointing out the missing intrinsic. Mind as well have it even if casting works. I have added it in 1.2.9.
